#!/usr/bin/env python3
import argparse
import base64
import hashlib
import json
import os
import pty
import shlex
import select
import signal
import struct
import subprocess
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, urlparse


APP_DIR = os.path.dirname(os.path.abspath(__file__))
RESOURCE_TYPES = "pods,deployments,services,nodes,events"
WS_GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
CONFIG_DIR = os.path.join(os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config")), "kube-dash")
PREFERENCES_PATH = os.path.join(CONFIG_DIR, "preferences.json")
DEFAULT_PREFERENCES = {"groupByPrefix": True}


def kubectl(args, timeout=45):
    completed = subprocess.run(
        ["kubectl", *args],
        cwd=APP_DIR,
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    if completed.returncode != 0:
        message = completed.stderr.strip() or completed.stdout.strip() or "kubectl command failed"
        raise RuntimeError(message)
    return completed.stdout


def context_args(context):
    return ["--context", context] if context else []


def current_context():
    try:
        return kubectl(["config", "current-context"], timeout=10).strip()
    except Exception:
        return ""


def list_contexts():
    try:
        output = kubectl(["config", "get-contexts", "-o", "name"], timeout=10)
        return [line.strip() for line in output.splitlines() if line.strip()]
    except Exception:
        return []


def read_preferences():
    try:
        with open(PREFERENCES_PATH, "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except Exception:
        data = {}
    preferences = dict(DEFAULT_PREFERENCES)
    if isinstance(data, dict):
        if "groupByPrefix" in data:
            preferences["groupByPrefix"] = bool(data["groupByPrefix"])
    return preferences


def write_preferences(preferences):
    current = read_preferences()
    if isinstance(preferences, dict) and "groupByPrefix" in preferences:
        current["groupByPrefix"] = bool(preferences["groupByPrefix"])
    os.makedirs(CONFIG_DIR, exist_ok=True)
    with open(PREFERENCES_PATH, "w", encoding="utf-8") as handle:
        json.dump(current, handle, indent=2, sort_keys=True)
        handle.write("\n")
    return current


def parse_cpu(value):
    text = value.strip()
    if text.endswith("m"):
        return int(float(text[:-1]))
    if text.endswith("n"):
        return int(float(text[:-1]) / 1000000)
    if text.endswith("u"):
        return int(float(text[:-1]) / 1000)
    return int(float(text) * 1000)


def parse_memory(value):
    text = value.strip()
    units = {
        "Ki": 1 / 1024,
        "Mi": 1,
        "Gi": 1024,
        "Ti": 1024 * 1024,
        "K": 1 / 1000,
        "M": 1000 / 1024,
        "G": 1000 * 1000 / 1024,
    }
    for suffix, multiplier in units.items():
        if text.endswith(suffix):
            return round(float(text[: -len(suffix)]) * multiplier, 2)
    return round(float(text) / 1024 / 1024, 2)


def parse_percent(value):
    text = value.strip().rstrip("%")
    return float(text) if text else 0


def parse_top_nodes(output):
    rows = []
    for line in output.splitlines():
        parts = line.split()
        if len(parts) < 5:
            continue
        rows.append(
            {
                "name": parts[0],
                "cpuMilli": parse_cpu(parts[1]),
                "cpuPercent": parse_percent(parts[2]),
                "memoryMi": parse_memory(parts[3]),
                "memoryPercent": parse_percent(parts[4]),
            }
        )
    return rows


def parse_top_pods(output):
    rows = []
    for line in output.splitlines():
        parts = line.split()
        if len(parts) < 4:
            continue
        rows.append(
            {
                "namespace": parts[0],
                "name": parts[1],
                "cpuMilli": parse_cpu(parts[2]),
                "memoryMi": parse_memory(parts[3]),
            }
        )
    return rows


def safe_kubectl_command(command):
    try:
        parts = shlex.split(command)
    except ValueError as exc:
        raise RuntimeError(str(exc)) from exc
    if not parts or parts[0] != "kubectl":
        raise RuntimeError("Only kubectl commands generated by this dashboard can run.")
    forbidden = {"exec", "attach", "proxy"}
    if any(part in forbidden for part in parts[1:]):
        raise RuntimeError("This command type has a dedicated dashboard action.")
    return parts


class Handler(SimpleHTTPRequestHandler):
    server_version = "kd/0.1"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=APP_DIR, **kwargs)

    def end_headers(self):
        self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def route_to_index_when_needed(self):
        parsed = urlparse(self.path)
        if parsed.path in {"", "/"} or "." not in os.path.basename(parsed.path):
            self.path = "/index.html"

    def do_HEAD(self):
        self.route_to_index_when_needed()
        super().do_HEAD()

    def do_GET(self):
        parsed = urlparse(self.path)
        if parsed.path in {"", "/"}:
            self.path = "/index.html"
            super().do_GET()
            return

        if parsed.path == "/api/shell":
            self.handle_shell(parsed)
            return

        if parsed.path == "/api/logs":
            self.handle_logs(parsed)
            return

        if parsed.path == "/api/run-stream":
            self.handle_run_stream(parsed)
            return

        if parsed.path == "/api/contexts":
            self.write_json({"currentContext": current_context(), "contexts": list_contexts()})
            return

        if parsed.path == "/api/preferences":
            self.write_json({"preferences": read_preferences(), "path": PREFERENCES_PATH})
            return

        if parsed.path == "/api/resources":
            query = parse_qs(parsed.query)
            context = (query.get("context") or [""])[0]
            try:
                output = kubectl([*context_args(context), "get", RESOURCE_TYPES, "-A", "-o", "json"])
                payload = json.loads(output)
                self.write_json({"context": context or current_context(), "resources": payload})
            except Exception as exc:
                self.write_json({"error": str(exc)}, status=502)
            return

        if parsed.path == "/api/describe":
            self.handle_describe(parsed)
            return

        if parsed.path == "/api/metrics":
            self.handle_metrics(parsed)
            return

        if "." not in os.path.basename(parsed.path):
            self.path = "/index.html"
        super().do_GET()

    def do_POST(self):
        parsed = urlparse(self.path)
        if parsed.path == "/api/run":
            self.handle_run()
            return
        if parsed.path == "/api/apply":
            self.handle_apply()
            return
        if parsed.path == "/api/preferences":
            self.handle_preferences()
            return
        self.send_error(404)

    def read_json_body(self):
        length = int(self.headers.get("Content-Length", "0"))
        body = self.rfile.read(length) if length else b"{}"
        return json.loads(body.decode("utf-8"))

    def handle_run(self):
        try:
            payload = self.read_json_body()
            command = payload.get("command", "")
            args = safe_kubectl_command(command)
            completed = subprocess.run(
                args,
                cwd=APP_DIR,
                capture_output=True,
                text=True,
                timeout=45,
                check=False,
            )
            self.write_json(
                {
                    "exitCode": completed.returncode,
                    "output": completed.stdout + completed.stderr,
                },
                status=200 if completed.returncode == 0 else 502,
            )
        except subprocess.TimeoutExpired as exc:
            output = ((exc.stdout or "") + (exc.stderr or ""))
            self.write_json({"exitCode": 124, "output": output + "\nCommand timed out."}, status=504)
        except Exception as exc:
            self.write_json({"exitCode": 1, "output": str(exc)}, status=400)

    def handle_apply(self):
        try:
            payload = self.read_json_body()
            context = payload.get("context", "")
            manifest = payload.get("manifest", "")
            if not manifest.strip():
                self.write_json({"exitCode": 1, "output": "Manifest is empty."}, status=400)
                return

            completed = subprocess.run(
                ["kubectl", *context_args(context), "apply", "-f", "-"],
                cwd=APP_DIR,
                input=manifest,
                capture_output=True,
                text=True,
                timeout=45,
                check=False,
            )
            self.write_json(
                {
                    "exitCode": completed.returncode,
                    "output": completed.stdout + completed.stderr,
                },
                status=200 if completed.returncode == 0 else 502,
            )
        except subprocess.TimeoutExpired as exc:
            output = ((exc.stdout or "") + (exc.stderr or ""))
            self.write_json({"exitCode": 124, "output": output + "\nApply timed out."}, status=504)
        except Exception as exc:
            self.write_json({"exitCode": 1, "output": str(exc)}, status=400)

    def handle_preferences(self):
        try:
            payload = self.read_json_body()
            preferences = write_preferences(payload.get("preferences", payload))
            self.write_json({"preferences": preferences, "path": PREFERENCES_PATH})
        except Exception as exc:
            self.write_json({"error": str(exc)}, status=400)

    def handle_describe(self, parsed):
        query = parse_qs(parsed.query)
        context = (query.get("context") or [""])[0]
        kind = (query.get("kind") or [""])[0]
        name = (query.get("name") or [""])[0]
        namespace = (query.get("namespace") or [""])[0]

        if not kind or not name:
            self.write_json({"error": "Missing kind or name"}, status=400)
            return

        command = ["describe", kind, name]
        if namespace:
            command.extend(["-n", namespace])

        try:
            output = kubectl([*context_args(context), *command])
            self.write_json({"description": output})
        except Exception as exc:
            self.write_json({"error": str(exc)}, status=502)

    def handle_metrics(self, parsed):
        query = parse_qs(parsed.query)
        context = (query.get("context") or [""])[0]
        payload = {"nodes": [], "pods": [], "errors": []}

        try:
            output = kubectl([*context_args(context), "top", "nodes", "--no-headers"], timeout=15)
            payload["nodes"] = parse_top_nodes(output)
        except Exception as exc:
            payload["errors"].append(f"nodes: {exc}")

        try:
            output = kubectl([*context_args(context), "top", "pods", "-A", "--no-headers"], timeout=15)
            payload["pods"] = parse_top_pods(output)
        except Exception as exc:
            payload["errors"].append(f"pods: {exc}")

        self.write_json(payload)

    def handle_shell(self, parsed):
        query = parse_qs(parsed.query)
        pod = (query.get("pod") or [""])[0]
        namespace = (query.get("namespace") or ["default"])[0]
        context = (query.get("context") or [""])[0]
        container = (query.get("container") or [""])[0]
        requested_shell = (query.get("shell") or [""])[0]

        if not pod:
            self.send_error(400, "Missing pod")
            return

        if not self.accept_websocket():
            return

        exec_base = [
            "kubectl",
            *context_args(context),
            "exec",
            "-it",
            pod,
            "-n",
            namespace,
            *(["-c", container] if container else []),
            "--",
        ]
        shells = [requested_shell] if requested_shell else ["/bin/sh", "/busybox/sh", "/bin/ash", "/bin/bash", "sh", "ash", "bash"]

        try:
            command, shell = self.find_shell(exec_base, shells)
            self.run_shell(command, shell)
        except Exception as exc:
            try:
                self.write_ws_frame(1, f"\r\nkd shell error: {exc}\r\n".encode("utf-8"))
            except Exception:
                pass

    def handle_logs(self, parsed):
        query = parse_qs(parsed.query)
        pod = (query.get("pod") or [""])[0]
        namespace = (query.get("namespace") or ["default"])[0]
        context = (query.get("context") or [""])[0]
        container = (query.get("container") or [""])[0]
        tail = (query.get("tail") or ["200"])[0]

        if not pod:
            self.send_error(400, "Missing pod")
            return

        if not self.accept_websocket():
            return

        command = [
            "kubectl",
            *context_args(context),
            "logs",
            pod,
            "-n",
            namespace,
            "--tail",
            tail,
            "-f",
            *(["-c", container] if container else []),
        ]

        try:
            self.run_stream(command, "logs")
        except Exception as exc:
            try:
                self.write_ws_frame(1, f"\nkd logs error: {exc}\n".encode("utf-8"))
            except Exception:
                pass

    def handle_run_stream(self, parsed):
        query = parse_qs(parsed.query)
        command = (query.get("command") or [""])[0]
        try:
            args = safe_kubectl_command(command)
        except Exception as exc:
            self.send_error(400, str(exc))
            return

        if not self.accept_websocket():
            return

        try:
            self.run_stream(args, "command")
        except Exception as exc:
            try:
                self.write_ws_frame(1, f"\nkd command error: {exc}\n".encode("utf-8"))
            except Exception:
                pass

    def find_shell(self, exec_base, shells):
        errors = []
        for shell in shells:
            if not shell:
                continue
            command = [*exec_base, shell]
            probe = [*exec_base, shell, "-c", "printf ok"]
            try:
                completed = subprocess.run(
                    probe,
                    cwd=APP_DIR,
                    capture_output=True,
                    text=True,
                    timeout=8,
                    check=False,
                )
            except Exception as exc:
                errors.append(f"{shell}: {exc}")
                continue
            if completed.returncode == 0:
                return command, shell
            message = (completed.stderr or completed.stdout).strip().splitlines()[-1:] or ["not available"]
            errors.append(f"{shell}: {message[0]}")
        raise RuntimeError("No interactive shell was found in this container. Tried: " + ", ".join(shell for shell in shells if shell))

    def run_shell(self, command, shell):
        pid, fd = pty.fork()
        if pid == 0:
            os.environ.setdefault("TERM", "xterm")
            os.execvp(command[0], command)

        self.write_ws_frame(1, ("Connected: " + " ".join(command) + "\r\n").encode("utf-8"))
        self.connection.setblocking(False)
        try:
            while True:
                readable, _, _ = select.select([self.connection, fd], [], [], 0.1)
                if fd in readable:
                    try:
                        data = os.read(fd, 4096)
                    except OSError:
                        break
                    if not data:
                        break
                    self.write_ws_frame(1, data)

                if self.connection in readable:
                    frame = self.read_ws_frame()
                    if frame is None:
                        break
                    opcode, payload = frame
                    if opcode == 8:
                        break
                    if opcode == 9:
                        self.write_ws_frame(10, payload)
                    if opcode in (1, 2) and payload:
                        os.write(fd, payload)
        finally:
            try:
                os.close(fd)
            except OSError:
                pass
            try:
                child, _ = os.waitpid(pid, os.WNOHANG)
                if child == 0:
                    os.kill(pid, signal.SIGTERM)
                    os.waitpid(pid, 0)
            except ChildProcessError:
                pass
            except ProcessLookupError:
                pass

    def run_stream(self, command, label):
        process = subprocess.Popen(
            command,
            cwd=APP_DIR,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
        )
        self.write_ws_frame(1, (f"Connected {label}: " + " ".join(command) + "\n").encode("utf-8"))
        self.connection.setblocking(False)
        try:
            while True:
                sources = [self.connection]
                if process.stdout:
                    sources.append(process.stdout)
                readable, _, _ = select.select(sources, [], [], 0.1)

                if process.stdout in readable:
                    data = process.stdout.read1(4096)
                    if data:
                        self.write_ws_frame(1, data)
                    elif process.poll() is not None:
                        break

                if self.connection in readable:
                    frame = self.read_ws_frame()
                    if frame is None:
                        break
                    opcode, payload = frame
                    if opcode == 8:
                        break
                    if opcode == 9:
                        self.write_ws_frame(10, payload)

                if process.poll() is not None:
                    break
        finally:
            if process.poll() is None:
                process.terminate()
                try:
                    process.wait(timeout=2)
                except subprocess.TimeoutExpired:
                    process.kill()

    def read_ws_frame(self):
        header = self.recv_exact(2)
        if not header:
            return None

        first, second = header
        opcode = first & 0x0F
        masked = second & 0x80
        length = second & 0x7F
        if length == 126:
            length = struct.unpack("!H", self.recv_exact(2))[0]
        elif length == 127:
            length = struct.unpack("!Q", self.recv_exact(8))[0]

        mask = self.recv_exact(4) if masked else b""
        payload = self.recv_exact(length) if length else b""
        if masked and payload:
            payload = bytes(byte ^ mask[index % 4] for index, byte in enumerate(payload))
        return opcode, payload

    def recv_exact(self, length):
        chunks = []
        remaining = length
        while remaining:
            try:
                chunk = self.connection.recv(remaining)
            except BlockingIOError:
                select.select([self.connection], [], [], 1)
                continue
            if not chunk:
                return b""
            chunks.append(chunk)
            remaining -= len(chunk)
        return b"".join(chunks)

    def write_ws_frame(self, opcode, payload):
        length = len(payload)
        if length < 126:
            header = struct.pack("!BB", 0x80 | opcode, length)
        elif length < 65536:
            header = struct.pack("!BBH", 0x80 | opcode, 126, length)
        else:
            header = struct.pack("!BBQ", 0x80 | opcode, 127, length)
        self.connection.sendall(header + payload)

    def accept_websocket(self):
        key = self.headers.get("Sec-WebSocket-Key")
        if self.headers.get("Upgrade", "").lower() != "websocket" or not key:
            self.send_error(400, "Expected WebSocket upgrade")
            return False
        if not self.is_local_origin():
            self.send_error(403, "WebSocket origin is not allowed")
            return False

        accept = base64.b64encode(hashlib.sha1((key + WS_GUID).encode("ascii")).digest()).decode("ascii")
        self.send_response(101, "Switching Protocols")
        self.send_header("Upgrade", "websocket")
        self.send_header("Connection", "Upgrade")
        self.send_header("Sec-WebSocket-Accept", accept)
        self.end_headers()
        return True

    def is_local_origin(self):
        origin = self.headers.get("Origin")
        if not origin:
            return True
        parsed = urlparse(origin)
        host = parsed.hostname or ""
        return host in {"localhost", "127.0.0.1", "::1"}

    def log_message(self, fmt, *args):
        print("%s - %s" % (self.address_string(), fmt % args))

    def write_json(self, payload, status=200):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def main():
    parser = argparse.ArgumentParser(description="Serve kd with a local kubectl bridge.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", default=8765, type=int)
    args = parser.parse_args()

    server = ThreadingHTTPServer((args.host, args.port), Handler)
    print(f"kd is running at http://{args.host}:{args.port}")
    print("Press Ctrl+C to stop.")
    server.serve_forever()


if __name__ == "__main__":
    main()
